# Keybindings

bind 1 select-window -t :1
bind 2 select-window -t :2
bind 3 select-window -t :3
bind 4 select-window -t :4
bind 5 select-window -t :5
bind 6 select-window -t :6
bind 7 select-window -t :7
bind 8 select-window -t :8
bind 9 select-window -t :9
bind t split-window -h
bind v split-window -v
bind k select-pane -U
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind f resize-pane -Z 

set -g @floax-change-path 'false'
set -g @sessionx-bind-window-mode 'w'
set -g @sessionx-bind 's'
set -g @floax-bind 'f'
set -g message-style bg=#1e1e2e,fg=#a6e3a1
set -g message-command-style bg=#313244,fg=#fab387
set -g display-time 1200
unbind e
unbind C-b
set -g prefix C-space
bind C-space send-prefix
# settings 
set -g default-terminal "${TERM}"
set -sg terminal-overrides ",*:RGB"
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1

# Status Bar
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

# Window buttons
set -g window-status-format "#{?window_bell_flag,#[fg=#f38ba8],#{?window_activity_flag,#[fg=#fab387],#[fg=#6c7086]}}●"
set -g window-status-current-format "#{?window_zoomed_flag,#[fg=#f9e2af],#[fg=#a6e3a1]}●"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=green,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# bell support 
set -g bell-action any
setw -g monitor-bell on
set -g visual-bell off
# activity support
set -g visual-activity off 
set -g visual-silence off
setw -g monitor-activity on
setw -g window-status-activity-style "fg=colour214"
set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tpm'

if "test ! -d ~/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm'"

run '~/.config/tmux/plugins/tpm/tpm'
