name: Release Please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: .github/release-please-config.json

  build:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - name: Build WSL image
        run: |
          NIX_PATH=$(which nix)
          sudo -E $NIX_PATH run .#nixosConfigurations.wsl.config.system.build.tarballBuilder --print-build-logs

      - name: Rename artifact
        run: |
          VERSION="${{ needs.release.outputs.tag_name }}"
          mv nixos.wsl "nixos-${VERSION}.wsl"

      - name: Upload Artifact to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release.outputs.tag_name }} nixos-${{ needs.release.outputs.tag_name }}.wsl --clobber

      - name: Rollback Release on Failure
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ needs.release.outputs.tag_name }} --yes --cleanup-tag
